clusterName: ace-spoke

collectors:
  daemon:
    suffix: agent
    enabled: true
    scrape_configs_file: "config/kubelet_scrape_configs.yaml"
    labels:
      otel-collector-type: daemonset
    targetAllocator:
      enabled: true
      serviceAccount: targetallocator
      image: ghcr.io/open-telemetry/opentelemetry-operator/target-allocator:main
      allocationStrategy: per-node
      prometheusCR:
        enabled: true
        podMonitorSelector: {}
        scrapeInterval: "30s"
        serviceMonitorSelector: {}
    config:
      receivers:
        k8sobjects:
          auth_type: serviceAccount
          objects:
            - name: namespaces
      exporters:
        otlp:
          endpoint: opentelemetry-kube-stack-gateway-collector.monitoring.svc.cluster.local:4317
          tls:
            insecure: true
        debug:
          verbosity: detailed
      processors:
        k8sattributes:
          extract:
            metadata:
              - k8s.namespace.name
            labels:
              - tag_name: ace.client
                key: ace.appscode.com/client-org
                from: namespace
      service:
        pipelines:
          metrics:
            receivers: [ prometheus ]
            processors: [ k8sattributes ]
            exporters: [ debug,otlp ]
          traces: null
          logs:
            receivers: [filelog, k8sobjects]
            processors: [k8sattributes]
            exporters: [debug, otlp]
    presets:
      logsCollection:
        enabled: true
      hostMetrics:
        enabled: false
      kubeletMetrics:
        enabled: false
      kubernetesAttributes:
        enabled: true

  cluster:
    suffix: gateway
    enabled: true
    labels:
      otel-collector-type: deployment
    image:
      repository: rokibulhasan114/opentelemetry-collector-ace
      tag: v0.1.0
      pullPolicy: Always
    env:
      - name: CLICKHOUSE_USERNAME
        valueFrom:
          secretKeyRef:
            name: ch-auth
            key: username
      - name: CLICKHOUSE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: ch-auth
            key: password
    presets:
      clusterMetrics:
        enabled: false
    config:
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
              include_metadata: true
            http:
              endpoint: 0.0.0.0:4318
              include_metadata: true
      extensions:
        headers_setter:
          headers:
            - action: upsert
              key: THANOS-TENANT
              from_context: tenant-id
      processors:
        k8sattributes:
          extract:
            metadata:
              - k8s.namespace.name
            labels:
              - tag_name: ace.client
                key: ace.appscode.com/client-org
                from: namespace
        groupbyattrs:
          keys: [source_id]
        transform/tenant:
          error_mode: ignore
          metric_statements:
            - context: resource
              statements:
                - set(resource.attributes["tenant"], "default")
                - set(resource.attributes["tenant"], resource.attributes["k8s.namespace.name"])
                  where resource.attributes["ace.client"] == "true"
        groupbyattrs/tenant:
          keys: [tenant]
        context/tenant:
          actions:
            - action: upsert
              key: tenant-id
              value: anonymous
              from_attribute: tenant
        batch/tenant:
          send_batch_size: 1000
          send_batch_max_size: 2000
          timeout: 1s
          metadata_keys:
            - tenant-id
      exporters:
        debug:
          verbosity: detailed
        prometheusremotewrite:
          endpoint: "http://10.2.0.141/receiver/api/v1/receive"
          auth:
            authenticator: headers_setter
        clickhouse:
          endpoint: "tcp://10.2.0.141:9000"
          username: "admin"
          password: "D4NT8ephEUHfVgh6"
          database: "default"
          create_schema: false
          logs_table_name: otel_logs
          timeout: 10s
          sending_queue:
            queue_size: 10000
          retry_on_failure:
            enabled: true
            initial_interval: 5s
            max_interval: 30s
            max_elapsed_time: 300s
      service:
        extensions: [headers_setter]
        pipelines:
          logs:
            receivers: [otlp]
            exporters: [clickhouse]
          metrics:
            receivers: [ otlp ]
            processors: [ groupbyattrs, transform/tenant, groupbyattrs/tenant, context/tenant, batch/tenant]
            exporters: [ debug, prometheusremotewrite]
          traces: null

instrumentation:
  enabled: false
opAMPBridge:
  enabled: false
kubernetesServiceMonitors:
  enabled: true
kubeApiServer:
  enabled: false
kubelet:
  enabled: false
kubeControllerManager:
  enabled: false
kubeDns:
  enabled: false
kubeEtcd:
  enabled: false
kubeScheduler:
  enabled: false
kubeProxy:
  enabled: false
kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
