apiVersion: monitoring.k8s.appscode.com/v1alpha1
kind: Tenant
metadata:
  name: org1
spec:
  tenantID: "org1"
  telemetryStackRef:
    name: ts-1
  metrics:
    targetEndpoint: "http://thanos-receiver.monitoring.svc:19291"
    retention:
      raw: "7d"
      fiveMinutes: "30d"
      oneHour: "180d"
#  ingestConfig:
#    dedicated: true
#    hashringConfig:
#      storageSize: "200Mi"
#      tsdbConfig:
#        retention: "2h"
#      replicas: 1
  logs:
    targetEndpoint: "http://thanos-receiver.monitoring.svc:19291"
    retention: "10m"

